apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorturl
  namespace: default
  labels:
    app: shorturl
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: shorturl
  template:
    metadata:
      labels:
        app: shorturl
    spec:
      containers:
      - name: shorturl
        image: registry.cn-shanghai.aliyuncs.com/ltinyho-web/shorturl:latest
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /app/etc
          name: cm-shorturl
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
        - name: aliyun
      volumes:
      - configMap:
          defaultMode: 420
          name: shorturl
          optional: false
        name: cm-shorturl

---

apiVersion: v1
kind: Service
metadata:
  name: shorturl-svc
  namespace: default
spec:
  ports:
    - port: 8080
  selector:
    app: shorturl

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: shorturl-hpa-c
  namespace: default
  labels:
    app: shorturl-hpa-c
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shorturl
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: shorturl-hpa-m
  namespace: default
  labels:
    app: shorturl-hpa-m
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shorturl
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shorturl
  namespace: default
data:
  shorturl-api.yaml: |
    Name: shorturl-api
    Host: 0.0.0.0
    Port: 8080
    Transform:
      Endpoints:
        - transform-svc:8080



